# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build-Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: NPM installations
      run: |
          npm install -g mocha
          npm install
    - name: NPM build
      run: npm build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: upload-site-data
        path: ./
  test:
    name: Test-Project
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: upload-site-data
    - name: Test artifact download
      run: ls -R
    - name: npm test
      run: |
        npm i -g mocha
        npm test
      env:
        CI: true
